name: Update sources using crowdin CLI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Crowdin CLI
        run: npm i -g @crowdin/cli

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install sphinx
        run: pip install -U sphinx

      - name: Generate pot files
        working-directory: docs
        run: sphinx-build -b gettext . _build/gettext

      - name: Upload pot files
        working-directory: docs
        run: crowdin upload sources --no-progress
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
